# Start with a base image containing Java runtime and Maven
FROM maven:3.8.4-openjdk-17 as build

# Copy the project files into the container
COPY src /mvn/spring-mvc-laptopshop/src
COPY pom.xml /mvn/spring-mvc-laptopshop

# Set the working directory
WORKDIR /mvn/spring-mvc-laptopshop

# Build the application as a WAR file and skip tests
RUN mvn clean package -DskipTests


FROM openjdk:17-slim


# Copy WAR file to the webapps directory in Tomcat
# Ensure that the path to the WAR file matches the actual file name generated by Maven
COPY --from=build /mvn/spring-mvc-laptopshop/target/*.war /mvn/spring-mvc-laptopshop/app.war

# Copy .env file into the container
COPY .env /mvn/spring-mvc-laptopshop/.env

EXPOSE 8000

ENTRYPOINT ["java", "-jar", "/mvn/spring-mvc-laptopshop/app.war"]

